<x-layout>
    <div class="max-w-7xl mx-auto mt-10 px-4 space-y-6">
        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex flex-wrap gap-4 justify-between items-center"><div><h1 class="text-2xl font-bold">Payroll Management</h1><p class="text-sm text-gray-500 mt-1">Set basic salaries, add bonuses or deductions, then calculate monthly pay.</p></div><form method="GET" class="flex gap-2"><input type="month" name="month" value="{{ $month }}" class="border rounded px-3 py-2"><button class="bg-gray-700 text-white rounded px-4 py-2">View</button></form></div>
            @if(session('status'))<p class="mt-4 text-green-600 text-sm">{{ session('status') }}</p>@endif
        </div>
        <div class="grid lg:grid-cols-2 gap-6">
            <form method="POST" action="{{ route('payroll.salaries.store', ['dptid'=>$dptid]) }}" class="bg-white rounded-lg shadow p-6 space-y-3">@csrf<h2 class="font-semibold text-lg">Basic Salary Management</h2><select name="user_id" class="w-full border rounded p-2" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} ({{ $employee->staff_id }})</option>@endforeach</select><input name="amount" type="number" min="0" step="0.01" placeholder="Monthly basic salary" class="w-full border rounded p-2" required><input name="effective_from" type="date" value="{{ now()->startOfMonth()->format('Y-m-d') }}" class="w-full border rounded p-2" required><button class="bg-indigo-600 text-white rounded px-4 py-2">Save Salary</button></form>
            <form method="POST" action="{{ route('payroll.adjustments.store', ['dptid'=>$dptid]) }}" class="bg-white rounded-lg shadow p-6 space-y-3">@csrf<h2 class="font-semibold text-lg">Bonus / Deduction</h2><select name="user_id" class="w-full border rounded p-2" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-3"><select name="type" class="border rounded p-2"><option value="bonus">Bonus</option><option value="deduction">Deduction</option></select><input name="amount" type="number" step="0.01" min="0.01" placeholder="Amount" class="border rounded p-2" required></div><input name="description" class="w-full border rounded p-2" placeholder="Reason / description" required><input name="payroll_month" type="month" value="{{ $month }}" class="w-full border rounded p-2" required><button class="bg-indigo-600 text-white rounded px-4 py-2">Add Adjustment</button></form>
        </div>
        <div class="bg-white rounded-lg shadow p-6"><div class="flex justify-between items-center mb-4"><h2 class="font-semibold text-lg">{{ \Carbon\Carbon::createFromFormat('Y-m', $month)->format('F Y') }} Payroll</h2><form method="POST" action="{{ route('payroll.calculate', ['dptid'=>$dptid]) }}">@csrf<input type="hidden" name="month" value="{{ $month }}"><button class="bg-green-600 text-white rounded px-4 py-2">Calculate Monthly Payroll</button></form></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="text-left p-3">Employee</th><th class="text-right p-3">Basic</th><th class="text-right p-3">Bonus</th><th class="text-right p-3">Deduction</th><th class="text-right p-3">Net Salary</th><th class="p-3"></th></tr></thead><tbody>@forelse($employees as $employee)@php($p=$payrolls->get($employee->id))<tr class="border-t"><td class="p-3">{{ $employee->name }}</td>@if($p)<td class="p-3 text-right">{{ number_format($p->basic_salary,2) }}</td><td class="p-3 text-right">{{ number_format($p->total_bonus,2) }}</td><td class="p-3 text-right">{{ number_format($p->total_deduction,2) }}</td><td class="p-3 text-right font-semibold">{{ number_format($p->net_salary,2) }}</td><td class="p-3 text-right"><a class="text-indigo-600" href="{{ route('payroll.slip',['dptid'=>$dptid,'payroll'=>$p]) }}">PDF Slip</a></td>@else<td colspan="5" class="p-3 text-gray-400">Not calculated</td>@endif</tr>@empty<tr><td colspan="6" class="p-4 text-gray-500">No employees found.</td></tr>@endforelse</tbody></table></div></div>
    </div>
</x-layout>
